FROM python:latest

WORKDIR /app

EXPOSE 80

RUN pip install --no-cache-dir --upgrade pip

COPY ./torn_website/requirements.txt ./

RUN pip install -r requirements.txt

COPY ./torn_website .

RUN mkdir static
RUN python manage.py collectstatic --noinput
RUN python manage.py makemigrations
RUN python manage.py migrate

CMD ["hypercorn", "--config", "hypercorn_config.toml", "torn_website.asgi:application"]
